Rest_Api : 
  type : rest
  resource: "@zenitthApiBundle/Resources/config/routing.yml"
  prefix : /api

Rest_Account : 
  type : rest
  resource: "@ZenitthUserBundle/Resources/config/routing.yml"
  prefix : /account