security:

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider:    fos_userbundle
                remember_me: true
                default_target_path: /admin
            remember_me:
                key:         %secret%
            anonymous:       true
            logout:          true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMINISTRATOR }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMINISTRATOR
        ROLE_SUPER_ADMIN: ROLE_ADMIN