<?php

namespace zenitth\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * brandsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class brandsRepository extends EntityRepository
{
	function findByBrandScore(){
		$qb = $this->getEntityManager()->createQueryBuilder();
        $qb->add('select', 'b')
           ->add('from', 'zenitthApiBundle:brands b')
           ->orderBy('b.score', 'DESC')
        ;

        return $qb->getQuery()->getResult();
	}
}
