<?php

namespace zenitth\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DefiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DefiRepository extends EntityRepository
{
}
